### ISSUE TITLE
Download Failed - server problem

### ISSUE THREAD

**Issue by ygee07** [0sc/activestorage-cloudinary-service#8]
Hi, 

I have this in my Gemfile, and am using the master branch since the released version seems to only support images.
```
gem 'cloudinary'
gem 'activestorage-cloudinary-service', git: 'https://github.com/0sc/activestorage-cloudinary-service'
```

and have this config/cloudinary.yml:
```
production:
  cloud_name: xxxxxxxx
  api_key: xxxxxxxx
  api_secret: xxxxxxxx
  enhance_image_tag: true
  static_image_support: true
```

I can now upload documents (.docx), but I'm now having problems downloading it both PDF and DOCX. Please help.

<img width="412" alt="screen shot 2018-07-12 at 11 49 29 am" src="https://user-images.githubusercontent.com/2621883/42611641-ad138738-85c9-11e8-825a-2ae1651c78de.png">
