### ISSUE TITLE
can you add secure: true  and  cdn_subdomain: true in options 

### ISSUE THREAD

**Issue by jbarnobal** [0sc/activestorage-cloudinary-service#9]
in cloudinary yml theres have a method like this
config.secure: true
congfig.cdn_subdomain: true to pass https and htpp. How to put this in service?

**Comment by jbarnobal** [comment]
Oh never mind i figured it out, this gem's save image in https, so i need to used ssl in production, thanks for this man

**Comment by 0sc** [comment]
Glad you figured it out 🥇 
It also flagged an error with the extra params setup. Just for any other person led here, currently, to explicitly pass extra params like `secure`, `cdn_subdomain` you'll have to set you cloudinary storage config like so:
```yml
cloudinary:
  service: Cloudinary
  cloud_name: CLOUDINARY_CLOUD_NAME
  api_key:    CLOUDINARY_API_KEY
  api_secret: CLOUDINARY_API_SECRET
  options:
    secure: true
    cdn_subdomain: true
```
_notice the options key_

This have been fixed here: https://github.com/0sc/activestorage-cloudinary-service/commit/f650cc51c21c1111194a2a66d6ec169b5d9145f3 and once it's merged and released you can specified extra params like so:

```yml
cloudinary:
  service: Cloudinary
  cloud_name: CLOUDINARY_CLOUD_NAME
  api_key:    CLOUDINARY_API_KEY
  api_secret: CLOUDINARY_API_SECRET
  secure: true
  cdn_subdomain: true
```
